// const chalk = require("chalk")
// console.log(chalk.bgGreen("Hello world"))
// console.log(chalk.green("Hello world"))
// console.log(chalk.green.bold("Hello world"))
// console.log(chalk.green.bold.inverse("Hello world"))